theme: jekyll-theme-minimal
title: Sheesoft - data and software service provider
description: Multicloud solutions
show_downloads: false
exclude:
  - bin
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/