theme: jekyll-theme-minimal
title: Sheesoft - data and software service provider
description: Multicloud solutions
show_downloads: false
exclude: [tmp, bin, Gemfile, Gemfile.lock, readme.txt, CNAME, ]